sudo: false

addons:
  apt:
    packages:
    - sox

cache:
  directories:
  - $HOME/env

language: python

notifications:
  email: false

python:
    - "2.7"
    - "3.4"
    - "3.5"

install:
    - pip install coveralls
    - pip install -r requirements.txt
    - pip install -e ./

script:
    - python --version
    - nosetests --with-coverage --cover-erase --cover-package=audiophile -v -w ./

after_success:
    - coveralls
    - pip uninstall -y audiophile

after_failure:
    - pip uninstall -y audiophile
